'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { InstitutionRegulation } from '@/modules/regulations/institution-regulation';

export function RegulationForm({ regulation, canManage }: { regulation: InstitutionRegulation | null; canManage: boolean }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file) { setMessage('Selecciona el reglamento institucional.'); return; } setBusy(true); setMessage(''); const form = new FormData(); form.append('regulation', file); const response = await fetch('/api/regulations', { method: 'POST', body: form }); const body = await response.json() as { error?: string }; if (!response.ok) { setMessage(body.error ?? 'No fue posible registrar el reglamento.'); setBusy(false); return; } router.refresh(); setMessage('Reglamento registrado. Los expedientes nuevos conservarán esta versión como contexto de apertura.'); setBusy(false); }
  return <section className="regulation-workspace"><div className="regulation-status"><p className="section-kicker">Versión aplicable</p><h2>{regulation ? `Versión ${regulation.version}` : 'Sin manual de contratación registrado'}</h2>{regulation ? <p><strong>{regulation.originalName}</strong><br />Registrado el {new Date(regulation.createdAt).toLocaleDateString('es-CO', { dateStyle: 'long' })}.</p> : <p>Sin una versión activa, las cotizaciones se conservan pero la etapa de mercado de los procesos nuevos queda bloqueada.</p>}</div>{canManage && <form className="regulation-upload" onSubmit={submit}><p className="section-kicker">Nueva versión</p><h2>Cargar manual de contratación aprobado</h2><p>La nueva versión se aplicará únicamente a procesos creados después de esta carga.</p><label className="file-picker"><span>Seleccionar manual de contratación</span><input type="file" accept="application/pdf,.docx,image/jpeg,image/png" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>{file && <p className="selected-regulation">Archivo seleccionado: <strong>{file.name}</strong></p>}<button className="primary-button" disabled={busy}>{busy ? 'Registrando…' : 'Registrar versión'}</button>{message && <p className="form-message" role="status">{message}</p>}</form>}</section>;
}
