import Link from 'next/link';
import { getAdminControlCenter } from '@/modules/admin/control-center';
import { listProcessesFor } from '@/modules/processes/process-queries';
import { WorkspaceShell } from '../_components/workspace-shell';
import { phaseLabel, ProcessStatus } from '../_components/process-status';
import { requireWorkspaceUser } from '../require-workspace-user';

export default async function AdminPage() {
  const user = await requireWorkspaceUser(['ARKA_ADMIN']);
  const processes = listProcessesFor(user);
  const workQueue = processes.filter((process) => !process.attorneyName || process.status === 'BLOCKED_REGULATION' || process.status === 'BLOCKED_MARKET_DATA');
  const control = getAdminControlCenter();
  return <WorkspaceShell user={user} activePath="/dashboard/admin"><div className="dossier-inbox">
    <header className="dossier-inbox-header"><div><p className="section-kicker">Arka Litigios IAG · Gestión documental</p><h1>Bandeja de trabajo</h1><p>Solo aparecen los expedientes que requieren una actuación administrativa o jurídica. El registro completo está en Todos los expedientes.</p></div><Link className="dossier-header-link" href="/dashboard/admin/processes">Ver todos los expedientes <span aria-hidden="true">→</span></Link></header>
    <section className="dossier-priorities" aria-label="Actuaciones prioritarias"><div><span className="priority-icon attention" aria-hidden="true">!</span><div><p>Asignación jurídica</p><strong>{control.counts.unassigned ? `${control.counts.unassigned} expediente${control.counts.unassigned === 1 ? '' : 's'} sin responsable jurídico` : 'No hay expedientes sin responsable jurídico'}</strong></div><Link href="/dashboard/admin/assignments">Gestionar →</Link></div><div><span className="priority-icon alert" aria-hidden="true">!</span><div><p>Bloqueos documentales</p><strong>{control.counts.blocked ? `${control.counts.blocked} actuación${control.counts.blocked === 1 ? '' : 'es'} bloqueada${control.counts.blocked === 1 ? '' : 's'}` : 'No hay actuaciones bloqueadas'}</strong></div><Link href="/dashboard/admin/alerts">Ver alertas →</Link></div></section>
    <section className="work-queue"><div className="dossier-table-heading"><div><p className="section-kicker">Pendientes de atención</p><h2>Procesos que requieren intervención</h2></div><span>{workQueue.length} {workQueue.length === 1 ? 'pendiente' : 'pendientes'}</span></div>{workQueue.length ? <div className="work-queue-list">{workQueue.map((process) => <Link className="work-item" href={`/dashboard/processes/${process.id}`} key={process.id}><span className="work-item-signal" aria-hidden="true">!</span><div className="work-item-main"><small>Proceso de contratación · {phaseLabel(process.phase)}</small><strong>{process.institutionName}</strong><span>{process.attorneyName ? `Responsable jurídico: ${process.attorneyName}` : 'Requiere asignar responsable jurídico'}</span></div><div className="work-item-status"><ProcessStatus status={process.status} /><small>Abierto el {new Date(process.createdAt).toLocaleDateString('es-CO', { day: '2-digit', month: 'short', year: 'numeric' })}</small></div><span className="work-item-open">Ver proceso <b aria-hidden="true">→</b></span></Link>)}</div> : <div className="dossier-empty"><strong>No hay procesos pendientes de atención.</strong><p>Los procesos registrados siguen disponibles en Todos los procesos.</p></div>}</section>
    <section className="dossier-footer-nav"><Link href="/dashboard/admin/institutions"><span aria-hidden="true">⌂</span><div><strong>Instituciones Educativas</strong><small>Relación de servicio, estado y responsables institucionales.</small></div><b>→</b></Link><Link href="/dashboard/admin/lawyers"><span aria-hidden="true">◌</span><div><strong>Equipo jurídico Arka</strong><small>Abogados disponibles y sus asignaciones vigentes.</small></div><b>→</b></Link><Link href="/dashboard/admin/audit"><span aria-hidden="true">≡</span><div><strong>Registro de actuaciones</strong><small>Trazabilidad de aperturas, asignaciones y cambios administrativos.</small></div><b>→</b></Link></section>
  </div></WorkspaceShell>;
}
