'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { InstitucionParaAcceso, RolAdministrable, UsuarioAdministrado } from '@/modules/access/supabase-user-administration';

const labels: Record<RolAdministrable, string> = { ADMINISTRADOR_ARKA: 'Administrador', ABOGADO_ARKA: 'Abogado', RECTOR_IE: 'Rector', APOYO_IE: 'Apoyo IE' };

export function UserAccessManagement({ usuarios: initialUsuarios, instituciones }: { usuarios: UsuarioAdministrado[]; instituciones: InstitucionParaAcceso[] }) {
  const router = useRouter(); const [usuarios, setUsuarios] = useState(initialUsuarios); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [rol, setRol] = useState<RolAdministrable>('ABOGADO_ARKA');
  const institucional = rol === 'RECTOR_IE' || rol === 'APOYO_IE';
  async function api(method: 'POST' | 'PATCH', body: object) { const response = await fetch('/api/admin/users', { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? 'No fue posible completar la acción.'); }
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage(''); try { await api('POST', { nombre: form.get('nombre'), correo: form.get('correo'), codigoRol: rol, idInstitucion: institucional ? form.get('idInstitucion') : null }); setMessage('Invitación enviada. La persona recibirá un enlace para definir su contraseña.'); event.currentTarget.reset(); setRol('ABOGADO_ARKA'); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible invitar a la persona.'); } finally { setBusy(false); } }
  async function action(usuario: UsuarioAdministrado, accion: 'REENVIAR' | 'CAMBIAR_ESTADO', activo?: boolean) { setBusy(true); setMessage(''); try { await api('PATCH', { idUsuario: usuario.id, accion, activo }); if (accion === 'CAMBIAR_ESTADO' && typeof activo === 'boolean') setUsuarios((current) => current.map((item) => item.id === usuario.id ? { ...item, activo } : item)); setMessage(accion === 'REENVIAR' ? `Se reenvió el enlace a ${usuario.correo}.` : `El acceso fue ${activo ? 'activado' : 'desactivado'}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible actualizar el acceso.'); } finally { setBusy(false); } }
  return <div className="management-layout"><section className="surface management-form"><p className="section-kicker">Nueva cuenta</p><h2>Invitar usuario</h2><p>El comité evaluador no se registra aquí: participa solo como información del proceso y no accede a la aplicación.</p><form onSubmit={invite}><label>Nombre completo<input required name="nombre" maxLength={160} /></label><label>Correo electrónico<input required name="correo" type="email" autoComplete="email" /></label><label>Rol<select value={rol} onChange={(event) => setRol(event.target.value as RolAdministrable)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{institucional && <label>Institución Educativa<select required name="idInstitucion" defaultValue=""><option value="" disabled>Seleccione una institución</option>{instituciones.map((institucion) => <option key={institucion.id} value={institucion.id}>{institucion.nombre}</option>)}</select></label>}{institucional && instituciones.length === 0 && <p className="form-message">Primero registre una Institución Educativa activa.</p>}<button className="primary-button" disabled={busy || (institucional && instituciones.length === 0)}>{busy ? 'Enviando…' : 'Enviar invitación'}</button></form>{message && <p className="form-message" role="status">{message}</p>}</section><section className="surface management-list"><div className="section-heading"><div><p className="section-kicker">Cuentas autorizadas</p><h2>Usuarios de LEXCON</h2></div><span>{usuarios.filter((usuario) => usuario.activo).length} activos</span></div><ul>{usuarios.map((usuario) => <li key={usuario.id}><div><strong>{usuario.nombre}</strong><span className={`service-state ${usuario.activo ? 'active' : 'ended'}`}>{usuario.activo ? 'Activo' : 'Desactivado'}</span><small>{labels[usuario.rol]}{usuario.institucion ? ` · ${usuario.institucion}` : ''}</small><small>{usuario.correo}</small></div><div className="row-actions">{usuario.activo && <button type="button" disabled={busy} onClick={() => action(usuario, 'REENVIAR')}>Reenviar enlace</button>}<button type="button" className={usuario.activo ? 'danger-button' : undefined} disabled={busy} onClick={() => action(usuario, 'CAMBIAR_ESTADO', !usuario.activo)}>{usuario.activo ? 'Desactivar' : 'Reactivar'}</button></div></li>)}</ul>{usuarios.length === 0 && <p>Aún no hay usuarios invitados.</p>}</section></div>;
}
