import { notFound } from 'next/navigation';
import { getProcessDetailForRuntime } from '@/modules/processes/process-queries';
import { WorkspaceShell } from '../../_components/workspace-shell';
import { phaseLabel, ProcessStatus } from '../../_components/process-status';
import { requireWorkspaceUser, workspacePath } from '../../require-workspace-user';
import { WorkflowActions } from './workflow-actions';
import { QuotationManager } from './quotation-manager';
import { MarketStudyDocument } from './market-study-document';
import { MarketStudyDataForm } from './market-study-data-form';
import { DownloadDocumentButton } from './download-document-button';
import { EvaluationTeamForm } from './evaluation-team-form';
import { analyzeEvaluationOffers } from '@/modules/automation/evaluation-act-docx';
import { contractFilename, contractTitle } from '@/modules/automation/selection-and-contractual-docx';

function sizeLabel(bytes: number): string {
  return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}


function approvalDeliveryLabel(status: string): string {
  if (status === 'DELIVERED') return 'Correo entregado a la IE';
  if (status === 'PENDING_CONFIGURATION') return 'Correo preparado; falta configurar el servicio de entrega';
  if (status === 'FAILED') return 'La entrega por correo debe reintentarse';
  return 'Comunicación preparada para envío';
}

function precontractualDocumentTitle(kind: string): string {
  return kind === 'PRELIMINARY_STUDY' ? 'Estudio previo o de conveniencia' : 'Invitación pública';
}

function precontractualDocumentPreview(kind: string): string {
  return kind === 'PRELIMINARY_STUDY'
    ? 'El Word incluye considerandos, fundamento, planeación, objeto, análisis del sector, presupuesto, CDP, requisitos, obligaciones, riesgos, cronograma y cierre institucional.'
    : 'El Word incluye capítulos de participación, requisitos habilitantes, evaluación, ejecución, cronograma y anexos de oferta económica, presentación, inhabilidades y transparencia.';
}

function processSituation(phase: string, status: string): string {
  if (status === 'BLOCKED_REGULATION') return 'Requiere reglamento aplicable';
  if (status === 'BLOCKED_MARKET_DATA') return 'Requiere cotizaciones con texto y valores legibles';
  if (status === 'PENDING_QUOTES') return 'Agregue las nuevas cotizaciones para continuar';
  if (status === 'CORRECTIONS_REQUESTED') return 'Atienda las correcciones jurídicas y recalcule el estudio';
  if (phase === 'BUDGET') return 'Estudio de mercado aprobado; pendiente de CDP';
  if (phase === 'PUBLICATION') return 'Documentos precontractuales aprobados; pendiente de publicación';
  if (phase === 'OFFERS') return 'Publicación registrada; pendiente de recepción de ofertas';
  if (phase === 'EVALUATION') return 'Ofertas recibidas; pendiente de evaluación';
  if (phase === 'DECISION') return 'Acta de selección preparada; pendiente de firmas y carga';
  if (phase === 'FORMALIZATION') return 'Acta de selección firmada; pendiente de Registro Presupuestal';
  if (phase === 'CONTRACTUAL_REVIEW') return 'Contrato y Acta de inicio pendientes de revisión jurídica';
  if (phase === 'CONTRACTUAL_PUBLICATION') return 'Documentos contractuales aprobados; pendiente de firmas y publicación en SECOP II';
  if (phase === 'EXECUTION') return 'Documentos firmados y publicación registrada; pendiente de recibidos a satisfacción';
  if (phase === 'LIQUIDATION_REVIEW') return 'Recibido a satisfacción final incorporado; Acta de liquidación pendiente de revisión jurídica';
  if (phase === 'POSTCONTRACTUAL') return 'Acta de liquidación aprobada jurídicamente; pendiente de firmas institucionales';
  if (phase === 'CLOSURE') return 'Ejecución registrada; pendiente de cierre';
  if (phase === 'CLOSED') return 'Proceso cerrado sin selección o con cierre registrado';
  return 'Cotizaciones analizadas';
}

export default async function ProcessDetailPage({ params }: { params: Promise<{ processId: string }> }) {
  const user = await requireWorkspaceUser();
  const { processId } = await params;
  const process = await getProcessDetailForRuntime(user, processId);
  if (!process) notFound();
  const isRemote = process.persistence === 'SUPABASE';
  const precontractualDrafts = process.drafts.filter((draft) => ['PRELIMINARY_STUDY', 'PUBLIC_INVITATION'].includes(draft.kind));
  const shouldShowMarketStudy = process.phase === 'MARKET' || process.phase === 'BUDGET';
  const rectorCanPublish = user.role === 'IE_RECTOR' && process.phase === 'PUBLICATION';
  const institutionCanReadEvaluation = (user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && ['EVALUATION', 'DECISION', 'FORMALIZATION', 'CONTRACTUAL_PUBLICATION', 'EXECUTION', 'LIQUIDATION_REVIEW', 'POSTCONTRACTUAL', 'CLOSURE', 'CLOSED'].includes(process.phase);
  const evaluationAssessment = !isRemote && institutionCanReadEvaluation ? await analyzeEvaluationOffers(process) : null;
  const evaluationDefinitive = process.actions.some((action) => action.action === 'EVALUATION_APPROVED');
  return <WorkspaceShell user={user} activePath={workspacePath(user.role)}><div className="page-stack process-detail">
    <header className="page-heading"><p className="section-kicker">{process.institutionName}</p><div className="heading-with-status"><div><h1>{phaseLabel(process.phase)}</h1><p>Proceso creado el {new Date(process.createdAt).toLocaleDateString('es-CO', { dateStyle: 'long' })} a partir de cotizaciones de mercado.</p></div><ProcessStatus status={process.status} /></div></header>
    {process.blockReason && <section className="block-notice" role="status"><strong>La actuación de mercado está bloqueada</strong><p>{process.blockReason} Las cotizaciones conservadas siguen disponibles como evidencia del expediente.</p></section>}
    <section className="detail-grid" aria-label="Información del expediente"><article className="surface"><p className="section-kicker">Responsables</p><h2>Intervinientes actuales</h2><dl className="detail-list"><div><dt>Responsable institucional</dt><dd>{process.responsibleName}</dd></div><div><dt>Abogado Arka</dt><dd>{process.attorneyName ?? 'Sin abogado asignado'}</dd></div></dl></article><article className="surface"><p className="section-kicker">Estado</p><h2>Actuación en curso</h2><dl className="detail-list"><div><dt>Fase</dt><dd>{phaseLabel(process.phase)}</dd></div><div><dt>Situación</dt><dd>{processSituation(process.phase, process.status)}</dd></div></dl></article></section>
    {isRemote && <section className="surface" role="status"><p className="section-kicker">Migración en curso</p><h2>Expediente remoto consultable</h2><p>Las cotizaciones y su trazabilidad ya residen en Supabase. La incorporación de nuevas cotizaciones, el análisis de mercado y las actuaciones posteriores se habilitarán cuando migre el worker y el flujo documental.</p></section>}
    {!isRemote && (user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && process.phase === 'MARKET' && <><MarketStudyDataForm processId={process.id} profile={process.marketStudy.profile} /><QuotationManager processId={process.id} quotations={process.quotations} /></>}
    {!isRemote && (user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && ['OFFERS', 'EVALUATION'].includes(process.phase) && <EvaluationTeamForm processId={process.id} evaluators={process.evaluationTeam?.evaluators ?? []} supervisor={process.evaluationTeam?.supervisor ?? null} />}
    {(user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && process.phase === 'BUDGET' && <section className="surface approval-next-step" aria-labelledby="approved-study-title"><div><p className="section-kicker">Siguiente actuación institucional</p><h2 id="approved-study-title">Estudio de mercado aprobado</h2><p>La revisión jurídica fue aprobada. Cargue el certificado de disponibilidad presupuestal para que LEXCON IAG prepare el estudio previo o de conveniencia y la invitación pública para revisión jurídica.</p></div><div className="approval-next-step-status"><strong>{process.approvalDelivery ? approvalDeliveryLabel(process.approvalDelivery.status) : 'Notificación institucional registrada'}</strong>{process.approvalDelivery && <small>{process.approvalDelivery.recipient}</small>}<a className="primary-button" href="#workflow-action">Cargar CDP</a></div></section>}
    {!isRemote && rectorCanPublish && precontractualDrafts.length > 0 && <section className="surface iag-drafts" aria-labelledby="approved-publication-documents-title"><div className="section-heading"><div><p className="section-kicker">Documentos aprobados</p><h2 id="approved-publication-documents-title">Paquete listo para publicación</h2><p>Descargue el estudio previo o de conveniencia y la invitación pública aprobados. Publíquelos en el canal definido por el reglamento institucional y registre la evidencia a continuación.</p></div><span>{precontractualDrafts.length} disponibles</span></div>{precontractualDrafts.map((draft) => <article key={draft.kind}><header><div><strong>{precontractualDocumentTitle(draft.kind)}</strong><span>Revisión jurídica aprobada</span></div><a className="secondary-button" href={`/api/processes/${process.id}/precontractual-documents/${draft.kind}`}>Descargar Word</a></header><pre aria-label={`Resumen de ${precontractualDocumentTitle(draft.kind)}`}>{precontractualDocumentPreview(draft.kind)}</pre></article>)}</section>}
    {user.role === 'ARKA_ATTORNEY' && process.phase === 'PRECONTRACTUAL' && precontractualDrafts.length > 0 && <section className="surface iag-drafts" aria-labelledby="precontractual-drafts-title"><div className="section-heading"><div><p className="section-kicker">Revisión jurídica precontractual</p><h2 id="precontractual-drafts-title">Documentos generados para revisión</h2><p>Descargue el Word completo y registre la decisión jurídica de esta etapa después de leerlo.</p></div><span>{precontractualDrafts.length} disponibles</span></div>{precontractualDrafts.map((draft) => <article key={draft.kind}><header><div><strong>{precontractualDocumentTitle(draft.kind)}</strong><span>{draft.status === 'APPROVED' ? 'Revisión jurídica registrada' : draft.status === 'CORRECTIONS_REQUESTED' ? 'Correcciones enviadas a la IE' : 'Pendiente de revisión jurídica'}</span></div><a className="secondary-button" href={`/api/processes/${process.id}/precontractual-documents/${draft.kind}`}>Descargar Word</a></header><pre aria-label={`Contenido de ${precontractualDocumentTitle(draft.kind)}`}>{precontractualDocumentPreview(draft.kind)}</pre></article>)}</section>}
    {user.role === 'ARKA_ATTORNEY' && process.phase === 'CONTRACTUAL_REVIEW' && <section className="surface iag-drafts" aria-labelledby="contractual-review-documents-title"><div className="section-heading"><div><p className="section-kicker">Revisión jurídica contractual</p><h2 id="contractual-review-documents-title">Contrato y Acta de inicio</h2><p>Revise los documentos completos antes de aprobarlos o solicitar correcciones. Durante esta fase no se muestran a Rectoría ni al funcionario institucional.</p></div><span>2 disponibles</span></div><article><header><div><strong>{contractTitle(process)}</strong><span>Pendiente de revisión jurídica</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/CONTRACT`} filename={contractFilename(process)} /></header><pre aria-label="Resumen del contrato">Incluye partes, considerandos, cláusulas, matriz de ítems, CDP, RP y el supervisor registrado por la IE.</pre></article><article><header><div><strong>Acta de inicio</strong><span>Pendiente de revisión jurídica</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/START_ACT`} filename="Acta_de_inicio.docx" /></header><pre aria-label="Resumen del Acta de inicio">Incorpora el supervisor y los requisitos de ejecución ya cumplidos.</pre></article></section>}
    {institutionCanReadEvaluation && <section className="surface iag-drafts" aria-labelledby="evaluation-act-title"><div className="section-heading"><div><p className="section-kicker">Evaluación institucional</p><h2 id="evaluation-act-title">{evaluationDefinitive ? 'Acta definitiva de evaluación' : 'Acta de evaluación generada'}</h2><p>{evaluationDefinitive ? 'El comité aprobó el análisis. La selección del proponente se documenta por separado en el Acta de selección.' : evaluationAssessment?.lowestEligible ? 'El acta presenta las ofertas habilitadas; el comité debe decidir expresamente cuál proponente selecciona.' : 'No se identificó una oferta habilitada. El expediente no puede avanzar a carta de aceptación, contratación ni RP.'}</p></div><span>1 disponible</span></div><article><header><div><strong>{evaluationDefinitive ? 'Acta definitiva de evaluación de ofertas' : 'Acta de evaluación de ofertas'}</strong><span>{evaluationDefinitive ? 'Análisis aprobado; selección pendiente o registrada en acta separada' : process.phase === 'CLOSED' ? 'Proceso cerrado sin selección' : evaluationAssessment?.lowestEligible ? 'Pendiente de decisión expresa del comité' : 'Pendiente de cierre sin selección'}</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/evaluation-act`} filename={evaluationDefinitive ? 'Acta_definitiva_de_evaluacion_de_ofertas.docx' : 'Acta_de_evaluacion_de_ofertas.docx'} /></header><pre aria-label="Resumen del acta de evaluación">Incluye integrantes del comité, supervisor, evaluación jurídica, técnica, financiera y económica, conclusión, observaciones y espacios de firma. No designa por sí sola al proponente seleccionado.</pre></article></section>}
    {(user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && process.phase === 'DECISION' && process.selectionDecision && <><section className="surface iag-drafts" aria-labelledby="selection-act-title"><div className="section-heading"><div><p className="section-kicker">Decisión del comité</p><h2 id="selection-act-title">Acta de selección de oferente</h2><p>El comité seleccionó expresamente a {process.selectionDecision.selectedSupplier}. Descargue el acta, obtenga las firmas del comité y cargue la versión firmada para continuar.</p></div><span>1 disponible</span></div><article><header><div><strong>Acta de selección de oferente</strong><span>Pendiente de firmas e incorporación al expediente</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/SELECTION_ACT`} filename="Acta_de_seleccion_de_oferente.docx" /></header><pre aria-label="Resumen del acta de selección">Incluye considerandos, resultado de evaluación, proponente seleccionado, motivación, órdenes y firmas del comité.</pre></article></section><WorkflowActions processId={process.id} phase={process.phase} role={user.role} blocked={Boolean(process.blockReason)} marketReady={process.status === 'RECEIVED'} marketStudyApproved={process.drafts.some((draft) => draft.kind === 'MARKET_STUDY' && draft.status === 'APPROVED')} eligibleSuppliers={[]} /></>}
    {(user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && ['FORMALIZATION', 'CONTRACTUAL_PUBLICATION', 'EXECUTION', 'LIQUIDATION_REVIEW', 'POSTCONTRACTUAL', 'CLOSURE', 'CLOSED'].includes(process.phase) && process.selectionDecision?.status === 'SIGNED_UPLOADED' && <section className="surface iag-drafts" aria-labelledby="acceptance-communication-title"><div className="section-heading"><div><p className="section-kicker">Aceptación de oferta</p><h2 id="acceptance-communication-title">Comunicación al proponente seleccionado</h2><p>El Acta de selección firmada está en el expediente. Descargue la comunicación de aceptación y continúe con el Registro Presupuestal.</p></div><span>1 disponible</span></div><article><header><div><strong>Comunicación de aceptación de oferta</strong><span>Lista para firma y comunicación institucional</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/ACCEPTANCE_COMMUNICATION`} filename="Comunicacion_de_aceptacion_de_oferta.docx" /></header><pre aria-label="Resumen de la comunicación de aceptación">Comunica el resultado institucional y exige completar los requisitos presupuestales y de ejecución.</pre></article></section>}
    {(user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && ['CONTRACTUAL_PUBLICATION', 'EXECUTION', 'POSTCONTRACTUAL', 'CLOSED'].includes(process.phase) && process.selectionDecision?.status === 'SIGNED_UPLOADED' && process.drafts.some((draft) => draft.kind === 'CONTRACT' && draft.status === 'APPROVED') && process.drafts.some((draft) => draft.kind === 'START_ACT' && draft.status === 'APPROVED') && <section className="surface iag-drafts" aria-labelledby="contractual-documents-title"><div className="section-heading"><div><p className="section-kicker">Etapa contractual</p><h2 id="contractual-documents-title">Contrato y Acta de inicio aprobados</h2><p>La abogada aprobó los documentos tras revisar el RP. Descárguelos, obtenga las firmas y registre la publicación en SECOP II antes de iniciar la ejecución.</p></div><span>2 disponibles</span><a className="primary-button" href="#workflow-action">Informar firmas y publicación</a></div><article><header><div><strong>{contractTitle(process)}</strong><span>Aprobado jurídicamente con el acto de selección y el RP</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/CONTRACT`} filename={contractFilename(process)} /></header></article><article><header><div><strong>Acta de inicio</strong><span>Aprobada jurídicamente para constancia del inicio real de ejecución</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/START_ACT`} filename="Acta_de_inicio.docx" /></header></article></section>}
    {user.role === 'ARKA_ATTORNEY' && process.phase === 'LIQUIDATION_REVIEW' && <section className="surface iag-drafts" aria-labelledby="liquidation-legal-review-title"><div className="section-heading"><div><p className="section-kicker">Revisión jurídica poscontractual</p><h2 id="liquidation-legal-review-title">Acta de liquidación del contrato</h2><p>Revise el Word antes de aprobarlo o solicitar correcciones. Mientras esta revisión está pendiente, el documento no se muestra a Rectoría ni al funcionario autorizado.</p></div><span>1 disponible</span></div><article><header><div><strong>Acta de liquidación del contrato</strong><span>Pendiente de revisión jurídica</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/LIQUIDATION_ACT`} filename="Acta_de_liquidacion_del_contrato.docx" /></header><pre aria-label="Resumen del Acta de liquidación">Incluye antecedentes FSE, recibidos parciales y final, balance contractual, declaraciones y espacios ampliados de firma.</pre></article></section>}
    {(user.role === 'IE_RECTOR' || user.role === 'IE_SUPPORT') && ['POSTCONTRACTUAL', 'CLOSED'].includes(process.phase) && process.drafts.some((draft) => draft.kind === 'LIQUIDATION_ACT' && draft.status === 'APPROVED') && <section className="surface iag-drafts" aria-labelledby="liquidation-act-title"><div className="section-heading"><div><p className="section-kicker">Etapa poscontractual</p><h2 id="liquidation-act-title">Acta de liquidación del contrato aprobada</h2><p>La revisión jurídica fue aprobada. Descargue el acta, obtenga las firmas y confirme la suscripción; si lo desea, cargue la versión firmada para conservarla en el expediente.</p></div><span>1 disponible</span><a className="primary-button" href="#workflow-action">Registrar firma del acta</a></div><article><header><div><strong>Acta de liquidación del contrato</strong><span>{process.phase === 'CLOSED' ? 'Firma registrada en el expediente' : 'Pendiente de firmas institucionales'}</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/generated-document/LIQUIDATION_ACT`} filename="Acta_de_liquidacion_del_contrato.docx" /></header><pre aria-label="Resumen del Acta de liquidación">Incluye antecedentes FSE, recibidos parciales y final, balance contractual, declaraciones y espacios ampliados de firma.</pre></article></section>}
    {institutionCanReadEvaluation && process.phase === 'CLOSED' && process.actions.some((action) => action.action === 'EVALUATION_NO_SELECTION_RECORDED') && <section className="surface iag-drafts" aria-labelledby="closure-declaration-title"><div className="section-heading"><div><p className="section-kicker">Cierre institucional</p><h2 id="closure-declaration-title">Acta de cierre y declaratoria de desierto</h2><p>La decisión de cierre quedó registrada. Descargue este Word para incorporarlo al expediente físico y realizar las publicaciones o comunicaciones institucionales que correspondan.</p></div><span>1 disponible</span></div><article><header><div><strong>Acta de cierre y declaratoria de desierto</strong><span>Proceso cerrado sin selección</span></div><DownloadDocumentButton href={`/api/processes/${process.id}/closure-declaration`} filename="Acta_de_cierre_y_declaratoria_de_desierto.docx" /></header><pre aria-label="Resumen del acta de cierre">Incluye considerandos, resultado de la evaluación, decisión motivada de declarar desierto, orden de incorporación al expediente y firmas.</pre></article></section>}
    {!isRemote && process.phase !== 'DECISION' && <WorkflowActions processId={process.id} phase={process.phase} role={user.role} blocked={Boolean(process.blockReason)} marketReady={process.status === 'RECEIVED'} marketStudyApproved={process.drafts.some((draft) => draft.kind === 'MARKET_STUDY' && draft.status === 'APPROVED')} eligibleSuppliers={evaluationAssessment?.evaluations.filter((evaluation) => evaluation.eligible).map((evaluation) => evaluation.offer.supplier).filter((supplier, index, all) => Boolean(supplier) && all.indexOf(supplier) === index) ?? []} />}
    {user.role === 'ARKA_ATTORNEY' && shouldShowMarketStudy && process.drafts.some((draft) => draft.kind === 'MARKET_STUDY') && <MarketStudyDocument process={process} status={process.drafts.find((draft) => draft.kind === 'MARKET_STUDY')!.status} />}
    <section className="surface document-list" aria-labelledby="documents-title"><div className="section-heading"><div><p className="section-kicker">Evidencia privada</p><h2 id="documents-title">Documentos del expediente</h2></div><span>{process.documents.length} {process.documents.length === 1 ? 'archivo' : 'archivos'}</span></div><ul>{process.documents.map((file) => <li key={file.fileId}><span className="document-mark" aria-hidden="true">DOC</span><div><strong>{file.originalName}</strong><small>{file.kind.replaceAll('_', ' ')} · {file.mimeType} · {sizeLabel(file.sizeBytes)} · recibido el {new Date(file.createdAt).toLocaleDateString('es-CO')}</small></div><a className="secondary-button" target="_blank" rel="noreferrer" href={`/api/processes/${process.id}/files/${file.fileId}`}>Abrir original</a></li>)}</ul></section>
    <section className="surface workflow-history"><div className="section-heading"><div><p className="section-kicker">Trazabilidad del flujo</p><h2>Actuaciones registradas</h2></div><span>{process.actions.length} registradas</span></div>{process.actions.length ? <ol>{process.actions.map((action, index) => <li key={`${action.action}-${index}`}><span aria-hidden="true">●</span><div><strong>{action.action.replaceAll('_', ' ')}</strong><small>{action.actorName} · {new Date(action.createdAt).toLocaleString('es-CO', { dateStyle: 'medium', timeStyle: 'short' })}{action.note ? ` · ${action.note}` : ''}</small></div></li>)}</ol> : <div className="empty-state"><strong>Aún no hay actuaciones posteriores a la apertura.</strong></div>}</section>
  </div></WorkspaceShell>;
}
